// Copyright (c) 2025-2026 Oleg Ivanchenko
// SPDX-License-Identifier: GPL-3.0-or-later

package mcpserver

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"sync"

	"github.com/danielgtaylor/huma/v2"
	"github.com/google/jsonschema-go/jsonschema"
)

// schemaDefsPrefix is where named nested types land: huma emits $ref values
// under this prefix and buildSchema attaches the matching $defs to the root.
const schemaDefsPrefix = "#/$defs/"

// schemas caches generated schemas per Go type. Schemas are immutable once
// built, and reusing the same pointer lets the SDK's SchemaCache skip
// re-resolving them when the server is rebuilt after a settings change.
var schemas sync.Map // reflect.Type -> *jsonschema.Schema

// schemaFor returns the JSON Schema (draft 2020-12) for T.
//
// It is generated by huma from the same struct tags REST v2 validates with
// (doc, enum, default, minimum, maximum, minLength, maxLength, pattern,
// required), so the SDK's validation of MCP tool arguments matches REST's
// validation of the equivalent parameters, and huma's strict default
// (additionalProperties: false) rejects misspelled arguments instead of
// silently ignoring them. Using huma also handles recursive types such as the
// category tree, which jsonschema-go's own inference rejects as a cycle.
func schemaFor[T any]() (*jsonschema.Schema, error) {
	t := reflect.TypeFor[T]()
	if cached, ok := schemas.Load(t); ok {
		return cached.(*jsonschema.Schema), nil
	}
	s, err := buildSchema(t)
	if err != nil {
		return nil, err
	}
	actual, _ := schemas.LoadOrStore(t, s)
	return actual.(*jsonschema.Schema), nil
}

// buildSchema generates and resolves the schema for a named struct type.
func buildSchema(t reflect.Type) (*jsonschema.Schema, error) {
	if t.Kind() != reflect.Struct || t.Name() == "" {
		return nil, fmt.Errorf("schema root %s must be a named struct", t)
	}
	registry := huma.NewMapRegistry(schemaDefsPrefix, huma.DefaultSchemaNamer)
	root, err := convertSchema(registry.Schema(t, false, ""))
	if err != nil {
		return nil, fmt.Errorf("converting schema for %s: %w", t, err)
	}
	if defs := registry.Map(); len(defs) > 0 {
		root.Defs = make(map[string]*jsonschema.Schema, len(defs))
		for name, def := range defs {
			converted, err := convertSchema(def)
			if err != nil {
				return nil, fmt.Errorf("converting %s%s: %w", schemaDefsPrefix, name, err)
			}
			root.Defs[name] = converted
		}
		if err := pruneUnreferencedRoot(root, huma.DefaultSchemaNamer(t, "")); err != nil {
			return nil, fmt.Errorf("pruning schema for %s: %w", t, err)
		}
	}
	if root.Type != "object" {
		return nil, fmt.Errorf("schema for %s has type %q, want object", t, root.Type)
	}
	if _, err := root.Resolve(&jsonschema.ResolveOptions{ValidateDefaults: true}); err != nil {
		return nil, fmt.Errorf("resolving schema for %s: %w", t, err)
	}
	return root, nil
}

// pruneUnreferencedRoot drops the registry's copy of the root type from
// $defs unless a $ref points back at it (a recursive root such as a category
// with children). The copy would otherwise double every tool schema that
// clients send to the model.
func pruneUnreferencedRoot(root *jsonschema.Schema, rootName string) error {
	self, ok := root.Defs[rootName]
	if !ok {
		return nil
	}
	delete(root.Defs, rootName)
	raw, err := json.Marshal(root)
	if err != nil {
		return err
	}
	if strings.Contains(string(raw), `"`+schemaDefsPrefix+rootName+`"`) {
		root.Defs[rootName] = self
	}
	if len(root.Defs) == 0 {
		root.Defs = nil
	}
	return nil
}

// convertSchema round-trips a huma schema through JSON into the jsonschema-go
// representation the SDK validates with. Keywords jsonschema-go does not model
// survive in Schema.Extra.
func convertSchema(h *huma.Schema) (*jsonschema.Schema, error) {
	raw, err := json.Marshal(h)
	if err != nil {
		return nil, err
	}
	var s jsonschema.Schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, err
	}
	return &s, nil
}
