// Copyright (c) 2025-2026 Oleg Ivanchenko
// SPDX-License-Identifier: GPL-3.0-or-later

package mcpserver

import (
	"context"
	"fmt"
	"math"
	"runtime/debug"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	v2 "github.com/olegiv/ocms-go/internal/api/v2"
)

// Outcomes recorded in the per-call log line.
const (
	outcomeOK              = "ok"
	outcomeToolError       = "tool_error"
	outcomeInternalError   = "internal_error"
	outcomeUnauthenticated = "unauthenticated"
)

// toolCall is what a tool handler knows about the call beyond its arguments.
type toolCall struct {
	// actor is who the v2 services see: the key with the drafts policy applied.
	actor    v2.Actor
	identity *identity
	settings Settings
}

// toolFunc is the signature of a tool implementation. Handlers are methods on
// *Module referenced as method expressions, e.g. (*Module).getPage.
type toolFunc[In, Out any] func(m *Module, ctx context.Context, call *toolCall, in In) (Out, error)

// registerTool binds a tool implementation to its catalog entry. Input and
// output schemas are generated by schemaFor, so the SDK validates arguments
// with the same constraints REST v2 applies and checks every result against
// its declared output schema.
//
// Schema errors are programming errors: registerTool panics, buildServer
// turns the panic into an Init error, and the module tests fail on it.
func registerTool[In, Out any](fn toolFunc[In, Out]) func(*Module, *mcp.Server, toolSpec) {
	return func(m *Module, srv *mcp.Server, spec toolSpec) {
		inSchema, err := schemaFor[In]()
		if err != nil {
			panic(fmt.Sprintf("tool %s: input schema: %v", spec.Name, err))
		}
		outSchema, err := schemaFor[Out]()
		if err != nil {
			panic(fmt.Sprintf("tool %s: output schema: %v", spec.Name, err))
		}
		mcp.AddTool(srv, &mcp.Tool{
			Name:         spec.Name,
			Title:        spec.Title,
			Description:  spec.Description,
			Annotations:  readOnlyAnnotations(spec.Title),
			InputSchema:  inSchema,
			OutputSchema: outSchema,
		}, wrapTool(m, spec, fn))
	}
}

// readOnlyAnnotations marks a tool as a read-only, idempotent query over the
// site's own data (a closed world).
func readOnlyAnnotations(title string) *mcp.ToolAnnotations {
	closedWorld := false
	return &mcp.ToolAnnotations{
		Title:          title,
		ReadOnlyHint:   true,
		IdempotentHint: true,
		OpenWorldHint:  &closedWorld,
	}
}

// wrapTool adapts a toolFunc to the SDK handler type. It
//   - recovers panics: the SDK runs handlers on its own goroutines, outside
//     chi's Recoverer, and has no recovery of its own, so an unrecovered
//     panic would take the whole process down;
//   - resolves the caller from TokenInfo and applies the drafts policy;
//   - turns errors into REST-shaped tool errors, scrubbing internal ones;
//   - logs one structured line per call.
func wrapTool[In, Out any](m *Module, spec toolSpec, fn toolFunc[In, Out]) mcp.ToolHandlerFor[In, Out] {
	return func(ctx context.Context, req *mcp.CallToolRequest, in In) (res *mcp.CallToolResult, out Out, err error) {
		start := time.Now()
		id, authenticated := identityFromRequest(req)
		outcome, errorCode := outcomeOK, ""
		defer func() {
			if p := recover(); p != nil {
				m.logger.Error("MCP tool panicked",
					"tool", spec.Name,
					"panic", fmt.Sprint(p),
					"stack", string(debug.Stack()))
				var zero Out
				res, out, err = nil, zero, internalToolError()
				outcome, errorCode = outcomeInternalError, codeInternal
			}
			m.logToolCall(req, spec.Name, id, outcome, errorCode, time.Since(start))
		}()

		if !authenticated {
			// The HTTP chain guarantees an identity; refuse rather than run
			// as nobody if that ever stops being true.
			outcome, errorCode = outcomeUnauthenticated, codeUnauthorized
			return nil, out, &toolError{Code: codeUnauthorized, Message: msgUnauthenticated}
		}

		settings := m.currentSettings()
		call := &toolCall{actor: actorFor(id, settings), identity: id, settings: settings}
		result, callErr := fn(m, ctx, call, in)
		if callErr != nil {
			te, internal := toToolError(callErr)
			outcome, errorCode = outcomeToolError, te.Code
			if internal {
				outcome = outcomeInternalError
				if isCancellation(callErr) {
					m.logger.Warn("MCP tool cancelled", "tool", spec.Name, "error", callErr)
				} else {
					m.logger.Error("MCP tool failed", "tool", spec.Name, "error", callErr)
				}
			}
			return nil, out, te
		}
		return nil, result, nil
	}
}

// logToolCall records one tools/call. Arguments and results are never
// logged: they can carry unpublished content.
func (m *Module) logToolCall(req *mcp.CallToolRequest, tool string, id *identity, outcome, errorCode string, elapsed time.Duration) {
	attrs := []any{
		"tool", tool,
		"outcome", outcome,
		"duration_ms", elapsed.Milliseconds(),
	}
	if id != nil {
		attrs = append(attrs, "api_key_id", id.key.ID, "api_key_prefix", id.key.KeyPrefix)
	}
	if req != nil {
		if client := req.ClientInfo(); client != nil {
			attrs = append(attrs, "client_name", client.Name, "client_version", client.Version)
		}
		if version := req.ProtocolVersion(); version != "" {
			attrs = append(attrs, "protocol_version", version)
		}
	}
	if errorCode != "" {
		attrs = append(attrs, "error_code", errorCode)
	}
	m.logger.Info("MCP tool call", attrs...)
}

// Pagination is the paging metadata shared by list results.
type Pagination struct {
	Total      int64 `json:"total" doc:"Total number of matching items."`
	Page       int   `json:"page" doc:"Current 1-indexed page."`
	PerPage    int   `json:"per_page" doc:"Items per page."`
	TotalPages int   `json:"total_pages" doc:"Number of pages at this page size."`
}

// newPagination builds paging metadata, mirroring REST v2's meta.pages.
func newPagination(total int64, page, perPage int) Pagination {
	p := Pagination{Total: total, Page: page, PerPage: perPage}
	if perPage > 0 && total > 0 {
		p.TotalPages = int(math.Ceil(float64(total) / float64(perPage)))
	}
	return p
}
