-- +goose Up
ALTER TABLE users ADD COLUMN avatar TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN linkedin_url TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN github_url TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE users DROP COLUMN github_url;
ALTER TABLE users DROP COLUMN linkedin_url;
ALTER TABLE users DROP COLUMN website_url;
ALTER TABLE users DROP COLUMN bio;
ALTER TABLE users DROP COLUMN avatar;
