// Copyright (c) 2025-2026 Oleg Ivanchenko
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addCategoryToPage = `-- name: AddCategoryToPage :exec
INSERT OR IGNORE INTO page_categories (page_id, category_id) VALUES (?, ?)
`

type AddCategoryToPageParams struct {
	PageID     int64 `json:"page_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) AddCategoryToPage(ctx context.Context, arg AddCategoryToPageParams) error {
	_, err := q.db.ExecContext(ctx, addCategoryToPage, arg.PageID, arg.CategoryID)
	return err
}

const categorySlugExists = `-- name: CategorySlugExists :one
SELECT COUNT(*) FROM categories WHERE slug = ?
`

func (q *Queries) CategorySlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, categorySlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const categorySlugExistsExcluding = `-- name: CategorySlugExistsExcluding :one
SELECT COUNT(*) FROM categories WHERE slug = ? AND id != ?
`

type CategorySlugExistsExcludingParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) CategorySlugExistsExcluding(ctx context.Context, arg CategorySlugExistsExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, categorySlugExistsExcluding, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const categorySlugExistsExcludingForLanguage = `-- name: CategorySlugExistsExcludingForLanguage :one
SELECT COUNT(*) FROM categories WHERE slug = ? AND id != ? AND language_id = ?
`

type CategorySlugExistsExcludingForLanguageParams struct {
	Slug       string        `json:"slug"`
	ID         int64         `json:"id"`
	LanguageID sql.NullInt64 `json:"language_id"`
}

func (q *Queries) CategorySlugExistsExcludingForLanguage(ctx context.Context, arg CategorySlugExistsExcludingForLanguageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, categorySlugExistsExcludingForLanguage, arg.Slug, arg.ID, arg.LanguageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const categorySlugExistsForLanguage = `-- name: CategorySlugExistsForLanguage :one
SELECT COUNT(*) FROM categories WHERE slug = ? AND language_id = ?
`

type CategorySlugExistsForLanguageParams struct {
	Slug       string        `json:"slug"`
	LanguageID sql.NullInt64 `json:"language_id"`
}

func (q *Queries) CategorySlugExistsForLanguage(ctx context.Context, arg CategorySlugExistsForLanguageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, categorySlugExistsForLanguage, arg.Slug, arg.LanguageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearPageCategories = `-- name: ClearPageCategories :exec
DELETE FROM page_categories WHERE page_id = ?
`

func (q *Queries) ClearPageCategories(ctx context.Context, pageID int64) error {
	_, err := q.db.ExecContext(ctx, clearPageCategories, pageID)
	return err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPagesByCategory = `-- name: CountPagesByCategory :one
SELECT COUNT(DISTINCT p.id) FROM pages p
INNER JOIN page_categories pc ON pc.page_id = p.id
WHERE pc.category_id = ?
`

func (q *Queries) CountPagesByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPagesByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, description, parent_id, position, language_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, slug, description, parent_id, position, created_at, updated_at, language_id
`

type CreateCategoryParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Position    int64          `json:"position"`
	LanguageID  sql.NullInt64  `json:"language_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.Position,
		arg.LanguageID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LanguageID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoriesForPage = `-- name: GetCategoriesForPage :many
SELECT c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id FROM categories c
INNER JOIN page_categories pc ON pc.category_id = c.id
WHERE pc.page_id = ?
ORDER BY c.name
`

func (q *Queries) GetCategoriesForPage(ctx context.Context, pageID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryAvailableTranslations = `-- name: GetCategoryAvailableTranslations :many
SELECT
    l.id as language_id,
    l.code as language_code,
    l.name as language_name,
    l.native_name as language_native_name,
    l.direction as language_direction,
    l.is_default as is_default,
    COALESCE(c.id, 0) as category_id,
    COALESCE(c.slug, '') as category_slug,
    COALESCE(c.name, '') as category_name
FROM languages l
LEFT JOIN (
    -- Get categories that are translations of the source category
    SELECT c.id, c.slug, c.name, t.language_id
    FROM categories c
    INNER JOIN translations t ON t.translation_id = c.id
    WHERE t.entity_type = 'category' AND t.entity_id = ?
    UNION
    -- Get the source category itself
    SELECT c.id, c.slug, c.name, c.language_id
    FROM categories c
    WHERE c.id = ?
    UNION
    -- Get categories where current category is a translation (sibling translations)
    SELECT c2.id, c2.slug, c2.name, c2.language_id
    FROM translations t
    INNER JOIN categories c2 ON (c2.id = t.entity_id OR c2.id = t.translation_id)
    WHERE t.entity_type = 'category'
    AND (t.entity_id = ? OR t.translation_id = ?)
) c ON c.language_id = l.id
WHERE l.is_active = 1
ORDER BY l.position
`

type GetCategoryAvailableTranslationsParams struct {
	EntityID      int64 `json:"entity_id"`
	ID            int64 `json:"id"`
	EntityID_2    int64 `json:"entity_id_2"`
	TranslationID int64 `json:"translation_id"`
}

type GetCategoryAvailableTranslationsRow struct {
	LanguageID         int64  `json:"language_id"`
	LanguageCode       string `json:"language_code"`
	LanguageName       string `json:"language_name"`
	LanguageNativeName string `json:"language_native_name"`
	LanguageDirection  string `json:"language_direction"`
	IsDefault          bool   `json:"is_default"`
	CategoryID         int64  `json:"category_id"`
	CategorySlug       string `json:"category_slug"`
	CategoryName       string `json:"category_name"`
}

// Get all available translations for a category (for language switcher)
func (q *Queries) GetCategoryAvailableTranslations(ctx context.Context, arg GetCategoryAvailableTranslationsParams) ([]GetCategoryAvailableTranslationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryAvailableTranslations,
		arg.EntityID,
		arg.ID,
		arg.EntityID_2,
		arg.TranslationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryAvailableTranslationsRow{}
	for rows.Next() {
		var i GetCategoryAvailableTranslationsRow
		if err := rows.Scan(
			&i.LanguageID,
			&i.LanguageCode,
			&i.LanguageName,
			&i.LanguageNativeName,
			&i.LanguageDirection,
			&i.IsDefault,
			&i.CategoryID,
			&i.CategorySlug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories WHERE id = ?
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LanguageID,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories WHERE slug = ?
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LanguageID,
	)
	return i, err
}

const getCategoryPath = `-- name: GetCategoryPath :many
WITH RECURSIVE category_path AS (
    SELECT cat.id, cat.name, cat.slug, cat.parent_id, 0 as depth
    FROM categories cat WHERE cat.id = ?
    UNION ALL
    SELECT c.id, c.name, c.slug, c.parent_id, cp.depth + 1
    FROM categories c
    INNER JOIN category_path cp ON c.id = cp.parent_id
)
SELECT id, name, slug, parent_id, depth FROM category_path ORDER BY depth DESC
`

type GetCategoryPathRow struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
	ParentID sql.NullInt64 `json:"parent_id"`
	Depth    int64         `json:"depth"`
}

func (q *Queries) GetCategoryPath(ctx context.Context, id int64) ([]GetCategoryPathRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryPathRow{}
	for rows.Next() {
		var i GetCategoryPathRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryUsageCounts = `-- name: GetCategoryUsageCounts :many
SELECT c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id, COUNT(pc.page_id) as usage_count
FROM categories c
LEFT JOIN page_categories pc ON pc.category_id = c.id
GROUP BY c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.language_id, c.created_at, c.updated_at
ORDER BY c.position, c.name
`

type GetCategoryUsageCountsRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Position    int64          `json:"position"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	LanguageID  sql.NullInt64  `json:"language_id"`
	UsageCount  int64          `json:"usage_count"`
}

func (q *Queries) GetCategoryUsageCounts(ctx context.Context) ([]GetCategoryUsageCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryUsageCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryUsageCountsRow{}
	for rows.Next() {
		var i GetCategoryUsageCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryUsageCountsByLanguage = `-- name: GetCategoryUsageCountsByLanguage :many
SELECT c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id, COUNT(p.id) as usage_count
FROM categories c
INNER JOIN page_categories pc ON pc.category_id = c.id
INNER JOIN pages p ON p.id = pc.page_id AND p.status = 'published' AND p.language_id = ?
GROUP BY c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.language_id, c.created_at, c.updated_at
ORDER BY c.position, c.name
`

type GetCategoryUsageCountsByLanguageRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Position    int64          `json:"position"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	LanguageID  sql.NullInt64  `json:"language_id"`
	UsageCount  int64          `json:"usage_count"`
}

// Category usage counts filtered by page language (for frontend sidebar)
func (q *Queries) GetCategoryUsageCountsByLanguage(ctx context.Context, languageID sql.NullInt64) ([]GetCategoryUsageCountsByLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryUsageCountsByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryUsageCountsByLanguageRow{}
	for rows.Next() {
		var i GetCategoryUsageCountsByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryUsageCountsWithLanguage = `-- name: GetCategoryUsageCountsWithLanguage :many
SELECT
    c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id,
    COUNT(pc.page_id) as usage_count,
    COALESCE(l.code, '') as language_code,
    COALESCE(l.name, '') as language_name
FROM categories c
LEFT JOIN page_categories pc ON pc.category_id = c.id
LEFT JOIN languages l ON l.id = c.language_id
GROUP BY c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.language_id, c.created_at, c.updated_at, l.code, l.name
ORDER BY c.position, c.name
`

type GetCategoryUsageCountsWithLanguageRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Position     int64          `json:"position"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LanguageID   sql.NullInt64  `json:"language_id"`
	UsageCount   int64          `json:"usage_count"`
	LanguageCode string         `json:"language_code"`
	LanguageName string         `json:"language_name"`
}

func (q *Queries) GetCategoryUsageCountsWithLanguage(ctx context.Context) ([]GetCategoryUsageCountsWithLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryUsageCountsWithLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryUsageCountsWithLanguageRow{}
	for rows.Next() {
		var i GetCategoryUsageCountsWithLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
			&i.UsageCount,
			&i.LanguageCode,
			&i.LanguageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryWithLanguage = `-- name: GetCategoryWithLanguage :one

SELECT
    c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id,
    COALESCE(l.code, '') as language_code,
    COALESCE(l.name, '') as language_name,
    COALESCE(l.native_name, '') as language_native_name,
    COALESCE(l.direction, 'ltr') as language_direction
FROM categories c
LEFT JOIN languages l ON l.id = c.language_id
WHERE c.id = ?
`

type GetCategoryWithLanguageRow struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Slug               string         `json:"slug"`
	Description        sql.NullString `json:"description"`
	ParentID           sql.NullInt64  `json:"parent_id"`
	Position           int64          `json:"position"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	LanguageID         sql.NullInt64  `json:"language_id"`
	LanguageCode       string         `json:"language_code"`
	LanguageName       string         `json:"language_name"`
	LanguageNativeName string         `json:"language_native_name"`
	LanguageDirection  string         `json:"language_direction"`
}

// Language-specific category queries
func (q *Queries) GetCategoryWithLanguage(ctx context.Context, id int64) (GetCategoryWithLanguageRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryWithLanguage, id)
	var i GetCategoryWithLanguageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LanguageID,
		&i.LanguageCode,
		&i.LanguageName,
		&i.LanguageNativeName,
		&i.LanguageDirection,
	)
	return i, err
}

const getDescendantIDs = `-- name: GetDescendantIDs :many
WITH RECURSIVE descendants AS (
    SELECT cat.id FROM categories cat WHERE cat.parent_id = ?
    UNION ALL
    SELECT c.id FROM categories c
    INNER JOIN descendants d ON c.parent_id = d.id
)
SELECT id FROM descendants
`

func (q *Queries) GetDescendantIDs(ctx context.Context, parentID sql.NullInt64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getDescendantIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories ORDER BY position, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByLanguage = `-- name: ListCategoriesByLanguage :many
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories
WHERE language_id = ?
ORDER BY position, name
`

func (q *Queries) ListCategoriesByLanguage(ctx context.Context, languageID sql.NullInt64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForSitemap = `-- name: ListCategoriesForSitemap :many
SELECT id, slug, updated_at FROM categories ORDER BY updated_at DESC
`

type ListCategoriesForSitemapRow struct {
	ID        int64     `json:"id"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListCategoriesForSitemap(ctx context.Context) ([]ListCategoriesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesForSitemapRow{}
	for rows.Next() {
		var i ListCategoriesForSitemapRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithLanguage = `-- name: ListCategoriesWithLanguage :many
SELECT
    c.id, c.name, c.slug, c.description, c.parent_id, c.position, c.created_at, c.updated_at, c.language_id,
    COALESCE(l.code, '') as language_code,
    COALESCE(l.name, '') as language_name
FROM categories c
LEFT JOIN languages l ON l.id = c.language_id
ORDER BY c.position, c.name
`

type ListCategoriesWithLanguageRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Position     int64          `json:"position"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LanguageID   sql.NullInt64  `json:"language_id"`
	LanguageCode string         `json:"language_code"`
	LanguageName string         `json:"language_name"`
}

func (q *Queries) ListCategoriesWithLanguage(ctx context.Context) ([]ListCategoriesWithLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesWithLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithLanguageRow{}
	for rows.Next() {
		var i ListCategoriesWithLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
			&i.LanguageCode,
			&i.LanguageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories WHERE parent_id = ? ORDER BY position, name
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID sql.NullInt64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByCategory = `-- name: ListPagesByCategory :many
SELECT DISTINCT p.id, p.title, p.slug, p.body, p.status, p.author_id, p.created_at, p.updated_at, p.published_at, p.featured_image_id, p.meta_title, p.meta_description, p.meta_keywords, p.og_image_id, p.no_index, p.no_follow, p.canonical_url, p.scheduled_at, p.language_id FROM pages p
INNER JOIN page_categories pc ON pc.page_id = p.id
WHERE pc.category_id = ?
ORDER BY p.updated_at DESC
LIMIT ? OFFSET ?
`

type ListPagesByCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

func (q *Queries) ListPagesByCategory(ctx context.Context, arg ListPagesByCategoryParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPagesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.FeaturedImageID,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImageID,
			&i.NoIndex,
			&i.NoFollow,
			&i.CanonicalUrl,
			&i.ScheduledAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories WHERE parent_id IS NULL ORDER BY position, name
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCategoryFromPage = `-- name: RemoveCategoryFromPage :exec
DELETE FROM page_categories WHERE page_id = ? AND category_id = ?
`

type RemoveCategoryFromPageParams struct {
	PageID     int64 `json:"page_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) RemoveCategoryFromPage(ctx context.Context, arg RemoveCategoryFromPageParams) error {
	_, err := q.db.ExecContext(ctx, removeCategoryFromPage, arg.PageID, arg.CategoryID)
	return err
}

const searchCategories = `-- name: SearchCategories :many
SELECT id, name, slug, description, parent_id, position, created_at, updated_at, language_id FROM categories
WHERE name LIKE '%' || ? || '%'
ORDER BY name LIMIT 20
`

func (q *Queries) SearchCategories(ctx context.Context, dollar_1 sql.NullString) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, searchCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LanguageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = ?, slug = ?, description = ?, parent_id = ?, position = ?, language_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, slug, description, parent_id, position, created_at, updated_at, language_id
`

type UpdateCategoryParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt64  `json:"parent_id"`
	Position    int64          `json:"position"`
	LanguageID  sql.NullInt64  `json:"language_id"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.Position,
		arg.LanguageID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LanguageID,
	)
	return i, err
}

const updateCategoryLanguage = `-- name: UpdateCategoryLanguage :exec
UPDATE categories SET language_id = ?, updated_at = ? WHERE id = ?
`

type UpdateCategoryLanguageParams struct {
	LanguageID sql.NullInt64 `json:"language_id"`
	UpdatedAt  time.Time     `json:"updated_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateCategoryLanguage(ctx context.Context, arg UpdateCategoryLanguageParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryLanguage, arg.LanguageID, arg.UpdatedAt, arg.ID)
	return err
}

const updateCategoryPosition = `-- name: UpdateCategoryPosition :exec
UPDATE categories SET position = ?, updated_at = ? WHERE id = ?
`

type UpdateCategoryPositionParams struct {
	Position  int64     `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdateCategoryPosition(ctx context.Context, arg UpdateCategoryPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryPosition, arg.Position, arg.UpdatedAt, arg.ID)
	return err
}
