// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: module_migrations.sql

package store

import (
	"context"
	"time"
)

const isModuleMigrationApplied = `-- name: IsModuleMigrationApplied :one
SELECT COUNT(*) FROM module_migrations
WHERE module = ? AND version = ?
`

type IsModuleMigrationAppliedParams struct {
	Module  string `json:"module"`
	Version int64  `json:"version"`
}

func (q *Queries) IsModuleMigrationApplied(ctx context.Context, arg IsModuleMigrationAppliedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isModuleMigrationApplied, arg.Module, arg.Version)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordModuleMigration = `-- name: RecordModuleMigration :exec
INSERT INTO module_migrations (module, version, applied_at)
VALUES (?, ?, ?)
`

type RecordModuleMigrationParams struct {
	Module    string    `json:"module"`
	Version   int64     `json:"version"`
	AppliedAt time.Time `json:"applied_at"`
}

func (q *Queries) RecordModuleMigration(ctx context.Context, arg RecordModuleMigrationParams) error {
	_, err := q.db.ExecContext(ctx, recordModuleMigration, arg.Module, arg.Version, arg.AppliedAt)
	return err
}
