// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_aliases.sql

package store

import (
	"context"
	"time"
)

const aliasExists = `-- name: AliasExists :one
SELECT EXISTS(SELECT 1 FROM page_aliases WHERE alias = ?)
`

func (q *Queries) AliasExists(ctx context.Context, alias string) (int64, error) {
	row := q.db.QueryRowContext(ctx, aliasExists, alias)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const aliasExistsExcludingPage = `-- name: AliasExistsExcludingPage :one
SELECT EXISTS(SELECT 1 FROM page_aliases WHERE alias = ? AND page_id != ?)
`

type AliasExistsExcludingPageParams struct {
	Alias  string `json:"alias"`
	PageID int64  `json:"page_id"`
}

func (q *Queries) AliasExistsExcludingPage(ctx context.Context, arg AliasExistsExcludingPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, aliasExistsExcludingPage, arg.Alias, arg.PageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const clearPageAliases = `-- name: ClearPageAliases :exec
DELETE FROM page_aliases WHERE page_id = ?
`

func (q *Queries) ClearPageAliases(ctx context.Context, pageID int64) error {
	_, err := q.db.ExecContext(ctx, clearPageAliases, pageID)
	return err
}

const createPageAlias = `-- name: CreatePageAlias :one

INSERT INTO page_aliases (page_id, alias, created_at)
VALUES (?, ?, ?)
RETURNING id, page_id, alias, created_at
`

type CreatePageAliasParams struct {
	PageID    int64     `json:"page_id"`
	Alias     string    `json:"alias"`
	CreatedAt time.Time `json:"created_at"`
}

// Page Alias queries
func (q *Queries) CreatePageAlias(ctx context.Context, arg CreatePageAliasParams) (PageAlias, error) {
	row := q.db.QueryRowContext(ctx, createPageAlias, arg.PageID, arg.Alias, arg.CreatedAt)
	var i PageAlias
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const getAliasesForPage = `-- name: GetAliasesForPage :many
SELECT id, page_id, alias, created_at FROM page_aliases WHERE page_id = ? ORDER BY created_at
`

func (q *Queries) GetAliasesForPage(ctx context.Context, pageID int64) ([]PageAlias, error) {
	rows, err := q.db.QueryContext(ctx, getAliasesForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageAlias{}
	for rows.Next() {
		var i PageAlias
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedPageByAlias = `-- name: GetPublishedPageByAlias :one
SELECT p.id, p.title, p.slug, p.body, p.status, p.author_id, p.created_at, p.updated_at, p.published_at, p.featured_image_id, p.meta_title, p.meta_description, p.meta_keywords, p.og_image_id, p.no_index, p.no_follow, p.canonical_url, p.scheduled_at, p.language_code, p.hide_featured_image, p.page_type, p.exclude_from_lists FROM pages p
INNER JOIN page_aliases pa ON pa.page_id = p.id
WHERE pa.alias = ? AND p.status = 'published'
`

func (q *Queries) GetPublishedPageByAlias(ctx context.Context, alias string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPublishedPageByAlias, alias)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.FeaturedImageID,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImageID,
		&i.NoIndex,
		&i.NoFollow,
		&i.CanonicalUrl,
		&i.ScheduledAt,
		&i.LanguageCode,
		&i.HideFeaturedImage,
		&i.PageType,
		&i.ExcludeFromLists,
	)
	return i, err
}
